"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color02)\
$username\
[](bg:color08 fg:color02)\
$directory\
[](fg:color08 bg:color13)\
$git_branch\
$git_status\
[](fg:color13 bg:color02)\
$time\
[ ](fg:color02)\
$line_break\
$character"""

palette = 'nord'

[palettes.nord]
color00 = '#2E3440'
color01 = '#3B4252'
color02 = '#434C5E'
color03 = '#4C566A'
color04 = '#D8DEE9'
color05 = '#E5E9F0'
color06 = '#ECEFF4'
color07 = '#8FBCBB'
color08 = '#5E81AC'
color09 = '#88C0D0'
color10 = '#81A1C1'
color11 = '#A3BE8C'
color12 = '#88C0D0'
color13 = '#81A1C1'
color14 = '#B48EAD'
color15 = '#5E81AC'

[username]
show_always = true
style_user = "bg:color02 fg:color05"
style_root = "bg:color02 fg:color05"
format = '[ $user ]($style)'

[directory]
style = "bg:color08 fg:color05"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:color05"
format = '[[ $symbol $branch ](fg:color05 bg:color13)]($style)'

[git_status]
style = "bg:color05"
format = '[[($all_status$ahead_behind )](fg:color05 bg:color13)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color02"
format = '[[ $time ](fg:color05 bg:color02)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color11)'
error_symbol = '[](bold fg:color14)'
vimcmd_symbol = '[󰁗](bold fg:color0B)'
vimcmd_replace_one_symbol = '[󰁗](bold fg:color0E)'
vimcmd_replace_symbol = '[󰁗](bold fg:color0E)'
vimcmd_visual_symbol = '[󰁗](bold fg:color05)'
