name: Build NixOS ISO

on:
  push:
    # branches:
    #   - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v20

      - name: Build NixOS ISO
        run: nix build .#ISO --print-build-logs

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nixos-iso
          path: result/iso/*.iso
