name: Build NixOS ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v20

      - name: Build NixOS ISO
        run: nix run nixpkgs#nixos-generators -- --format iso --flake .#installer -o result

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nixos-iso
          path: result/iso/*.iso
